export const LABEL = {
  LOGIN_FORM: {
    EMAIL: "email",
    PASSWORD: "mật khẩu",
    RE_PASSWORD: "xác nhận mật khẩu",
    FIRST_NAME: "họ",
    LAST_NAME: "tên",
  },
};

export const MESSAGES = {
  MSG_001: "Vui lòng nhập ${field}.",
  MSG_002: "Vui lòng chọn ${field}.",
  MSG_003: "${field} must be no more than ${max} characters long.",
  MSG_004: "${field} must be at least ${min} characters long.",
  MSG_005: "Định dạng email không đúng.",
  MSG_006: "Password must contain at least 1 lowercase letter and 1 number.",
  MSG_007: "Please check the checkbox.",
  MSG_008: "Please enter ${field} in hiragana.",
  MSG_009: "Password and confirm password do not match.",
  MSG_010: "Emoticons are not allowed.",
  MSG_014: "This tag has already been added before.",
  MSG_015: "You can only add up to 10 tags.",
  MSG_016: "Please enter no more than ${max} characters.",
  MSG_017: "You can only register up to 100 items.",
  MSG_021: "Please enter no more than ${max} characters for each field.",
  MSG_022: "Please check the agree checkbox.",
  MSG_023: "Please upload an image no larger than 30Mb.",
  MSG_024: "Please upload an image in jpg, jpeg, or png format.",
  MSG_025: "Please upload a video no larger than 512Mb.",
  MSG_026: "Please upload a video in mp4 or mov format.",
  MSG_027: "Please upload an audio no larger than 30Mb.",
  MSG_028: "Please upload an audio in mp3 format.",
  MSG_029: "You can only upload up to 3 files.",
  MSG_030: "Invalid date.",
  MSG_031:
    "Please set a password between 8 and 24 characters including letters and numbers.",
  MSG_032: "Please enter ${field} in hiragana.",
  MSG_033: "This activity name has already been registered before.",
  MSG_034: "Similar data has already been registered before.",
  MSG_035: "Please select a time frame.",
  MSG_036: "The caring doctor has already been registered before.",
  MSG_UPLOAD_FILE_TYPE:
    "Please upload a file in mp4, mov, mp3, jpg, jpeg, or png format.",
  MSG_037: "You need to agree to the terms of use.",
  MSG_038: "You need to agree to the privacy policy.",
  MSG_039: "Invalid date of birth.",
  MSG_040: "Please select the position type of Superwoman.",
  MSG_041: "New password and confirm password do not match.",
  MSG_RELATIONSHIP: "${field} has already been registered before.",
  MSG_UPLOAD_DOCUMENT_SIZE: "Please upload a document no larger than 30Mb.",
  MSG_UPLOAD_DOCUMENT_TYPE:
    "Please upload a document in PDF, Excel, Word, or text format.",
  MSG_UPLOAD_MAX_IMG:
    "Exceeded the maximum number of uploaded images (5 images).",
  MSG_ERROR_DELETE_DEPARTMENT:
    "Cannot delete this item because it has been used in previous records.",
  MSG_MAX_INVITATION: "Cannot add more than 10 items.",
  MSG_PHONE_NUMBER: "Invalid phone number format.",
  MSG_PHONE_NUMBER_2: "Invalid ${field} number format.",
  MSG_DUPLICATE_HOSPITAL:
    "The hospital name has already been registered before.",
  MSG_FACILITY_TYPE: "Please select the facility type.",
  MSG_FACILITY_WORK_TIME: "Please enter the working time of the facility.",
  MSG_FACILITY_DETAIL: "Please enter facility information.",
  MSG_MESSAGE_MAX_LENGTH:
    "Please enter a message no more than 1000 characters.",
  MSG_TAG_MAX_LENGTH: "Please enter no more than 10 characters.",
  MSG_042: "Please enter no more than ${max} characters.",
  MSG_043: "Please select the end time after the start time",
};
