export enum TRANSACTION_ENUM {
  INIT = 'INIT',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
}

export enum ORDER_STATUS_ENUM {
  PROCESSING = 'PROCESSING',
  INIT = 'INIT',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED',
}
