services:
  postgres:
    hostname: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - foodly-network
    ports:
      - '5432:5432'

  redis:
    hostname: redis
    image: redis:latest
    networks:
      - foodly-network

  # maildev:
  #   hostname: maildev
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - 1080:1080
  #     - 1025:1025
  #   volumes:
  #     - maildev_data:/data
  # networks:
  #   - foodly-network

  # api:
  #   hostname: api
  #   user: root
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6100:6100
  # networks:
  #   - foodly-network

volumes:
  postgres:
  maildev_data:

networks:
  foodly-network:
    driver: bridge
