# docker-compose.yml

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - nestjs-boilerplate-network

volumes:
  postgres:

networks:
  nestjs-boilerplate-network:
    driver: bridge
